# Generated by Django 5.0.4 on 2024-05-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_medicine_pet_product_alter_veterinary_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinary',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
